name: Create Hotfix Pull Request

on:
  push:
    branches:
      - 'hotfix/v**'

jobs:
  version-and-tag:
    name: Version and Tag
    runs-on: ubuntu-latest
    environment: Release
    outputs:
      version: ${{ steps.semrel.outputs.version }}
      tag_name: ${{ steps.semrel.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # By using the GITHUB_TOKEN, this workflow won't be triggered by itself
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run semantic-release
        id: semrel
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        run: |
          echo "🏷️ Running semantic-release (version, changelog, and tagging)"
          npx semantic-release --debug