# Deployment workflow - deploys from release/hotfix branches with manual approval
name: Deploy

on:
  push:
    branches:
      - 'release/v**'
      - 'hotfix/v**'

jobs:
  check-for-production-deployment:
    name: Check for Production Deployment
    runs-on: ubuntu-latest
    outputs:
      should_deploy_prod: ${{ steps.check_tags.outputs.should_deploy_prod }}
      production_version: ${{ steps.check_tags.outputs.production_version }}
      branch_type: ${{ steps.check_branch.outputs.branch_type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check branch type
        id: check_branch
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          if [[ "$BRANCH_NAME" == hotfix/* ]]; then
            echo "branch_type=hotfix" >> $GITHUB_OUTPUT
            echo "🔥 Detected hotfix branch: $BRANCH_NAME"
          elif [[ "$BRANCH_NAME" == release/* ]]; then
            echo "branch_type=release" >> $GITHUB_OUTPUT
            echo "🚀 Detected release branch: $BRANCH_NAME"
          else
            echo "branch_type=unknown" >> $GITHUB_OUTPUT
            echo "⚠️ Unknown branch type: $BRANCH_NAME"
          fi

      - name: Check for production deployment
        id: check_tags
        run: |
          echo "Checking for release tags on current commit..."

          # Get current commit SHA
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Current commit: $CURRENT_COMMIT"

          # Check if current commit has a release tag (semantic version format)
          RELEASE_TAG=$(git tag --points-at $CURRENT_COMMIT | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -1)

          if [ -n "$RELEASE_TAG" ]; then
            VERSION=${RELEASE_TAG#v}  # Remove 'v' prefix
            echo "should_deploy_prod=true" >> $GITHUB_OUTPUT
            echo "production_version=$VERSION" >> $GITHUB_OUTPUT
            echo "✅ Found release tag $RELEASE_TAG - production deployment approved"
          else
            echo "should_deploy_prod=false" >> $GITHUB_OUTPUT
            echo "production_version=" >> $GITHUB_OUTPUT
            echo "📦 No release tag found - development/staging deployment only"
          fi

  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [check-for-production-deployment]
    environment: Release  # 🔑 Manual approval required here!
    steps:
      - name: Dummy checkout and setup
        run: echo "Simulating repository checkout and AWS configuration..."

      - name: Dummy ECR login
        id: login-ecr
        run: |
          echo "Logging into Amazon ECR..."
          echo "registry=123456789.dkr.ecr.us-east-1.amazonaws.com" >> $GITHUB_OUTPUT
          echo "✅ Successfully logged into ECR"

      - name: Dummy image metadata preparation
        id: image_meta
        env:
          SHOULD_DEPLOY_PROD: ${{ needs.check-for-production-deployment.outputs.should_deploy_prod }}
          PRODUCTION_VERSION: ${{ needs.check-for-production-deployment.outputs.production_version }}
          BRANCH_TYPE: ${{ needs.check-for-production-deployment.outputs.branch_type }}
        run: |
          echo "Preparing Docker image metadata..."
          timestamp=$(date +%s)
          BRANCH_NAME="${{ github.ref_name }}"

          # Always create dev tag with branch info
          dev_tag="some.ecr.url:${BRANCH_TYPE}-${timestamp}-abc1234"
          tags="${dev_tag}"

          # Add production tag if this is an approved release
          if [ "$SHOULD_DEPLOY_PROD" = "true" ]; then
            prod_tag="some.ecr.url:${PRODUCTION_VERSION}"
            tags="${tags},${prod_tag}"
            echo "🎯 Production deployment enabled - adding production tag: $prod_tag"
          else
            echo "📦 Development/staging deployment only - no production tag"
          fi

          echo "tags=${tags}" >> $GITHUB_OUTPUT
          echo "timestamp=${timestamp}" >> $GITHUB_OUTPUT
          echo "dev_tag=${dev_tag}" >> $GITHUB_OUTPUT
          echo "🌿 Deploying from branch: $BRANCH_NAME"

      - name: Dummy Docker build
        run: |
          echo "Setting up Docker buildx..."
          echo "Building Docker image with multi-platform support..."
          echo "📦 Image built successfully for linux/amd64"
          echo "🔄 Loading image for asset extraction"

      - name: Dummy asset publishing
        env:
          BRANCH_TYPE: ${{ needs.check-for-production-deployment.outputs.branch_type }}
          SHOULD_DEPLOY_PROD: ${{ needs.check-for-production-deployment.outputs.should_deploy_prod }}
        run: |
          echo "Extracting assets from Docker container..."
          echo "Creating temporary container for asset extraction"
          echo "Extracting /usr/share/nginx/html/ directory"

          if [ "$SHOULD_DEPLOY_PROD" = "true" ]; then
            echo "Syncing assets to S3 production bucket..."
          else
            echo "Syncing assets to S3 ${BRANCH_TYPE} environment bucket..."
          fi

          echo "✅ Assets published to S3 successfully"
          echo "🧹 Cleaned up temporary files"

      - name: Dummy ECR image push
        env:
          SHOULD_DEPLOY_PROD: ${{ needs.check-for-production-deployment.outputs.should_deploy_prod }}
          PRODUCTION_VERSION: ${{ needs.check-for-production-deployment.outputs.production_version }}
          BRANCH_TYPE: ${{ needs.check-for-production-deployment.outputs.branch_type }}
        run: |
          echo "Pushing images to Amazon ECR..."
          timestamp=$(date +%s)
          echo "📤 Pushing ${BRANCH_TYPE} tag: ${BRANCH_TYPE}-${timestamp}-abc1234"

          if [ "$SHOULD_DEPLOY_PROD" = "true" ]; then
            echo "📤 Pushing production tag: ${PRODUCTION_VERSION}"
            echo "✅ Both ${BRANCH_TYPE} and production images pushed successfully to ECR"
          else
            echo "⏭️ Skipping production tag push (no approved release)"
            echo "✅ ${BRANCH_TYPE} image pushed successfully to ECR"
          fi

      - name: Dummy metadata update
        env:
          SHOULD_DEPLOY_PROD: ${{ needs.check-for-production-deployment.outputs.should_deploy_prod }}
          PRODUCTION_VERSION: ${{ needs.check-for-production-deployment.outputs.production_version }}
          BRANCH_TYPE: ${{ needs.check-for-production-deployment.outputs.branch_type }}
        run: |
          echo "Updating environment metadata files..."

          if [ "$BRANCH_TYPE" = "release" ]; then
            echo "📝 Updated dev metadata: devt-webapp-meta.json"
            echo "📝 Updated staging metadata: stag-webapp-meta.json"
          elif [ "$BRANCH_TYPE" = "hotfix" ]; then
            echo "📝 Updated staging metadata: stag-webapp-meta.json (hotfix testing)"
          fi

          # Update production metadata only for approved releases
          if [ "$SHOULD_DEPLOY_PROD" = "true" ]; then
            echo "📝 Updated production metadata: prod-webapp-meta.json"
            echo "✅ Updated production metadata for version ${PRODUCTION_VERSION}"
          else
            echo "⏭️ Skipping production metadata update (no approved release)"
          fi

      - name: Deployment summary
        env:
          SHOULD_DEPLOY_PROD: ${{ needs.check-for-production-deployment.outputs.should_deploy_prod }}
          PRODUCTION_VERSION: ${{ needs.check-for-production-deployment.outputs.production_version }}
          BRANCH_TYPE: ${{ needs.check-for-production-deployment.outputs.branch_type }}
        run: |
          echo "🎉 Deployment completed successfully!"
          echo "🌿 Branch: ${{ github.ref_name }}"
          echo "📋 Type: ${BRANCH_TYPE}"

          if [ "$SHOULD_DEPLOY_PROD" = "true" ]; then
            echo "🚀 Production deployment: ✅ (version ${PRODUCTION_VERSION})"
            echo "🌍 Environments updated: Development, Staging, Production"
          else
            echo "🚀 Production deployment: ❌ (no release tag)"
            if [ "$BRANCH_TYPE" = "release" ]; then
              echo "🌍 Environments updated: Development, Staging"
            else
              echo "🌍 Environments updated: Staging (hotfix testing)"
            fi
          fi
